import React,{ useState } from 'react'
import './Product.css'

const ProductDisplay=(props)=>{
    const {product}=props;



    const [mainImage, setMainImage] = useState(product.profilePic[0].original); // State to track the main image
    // Function to handle image click and swap with the main image
    const handleImageClick = (image) => {
        setMainImage(image);
    };


    return(
        <div className='productdisplay'>
          <div className="productdisplay-left">
            <div className="productdisplay-img-list">
                {/* Map over the profilePic array and render each image */}
                {product.profilePic.map((pic, index) => (
                        <React.Fragment key={`${index}-${pic.original}`}>
                            {/* onClick event to swap images */}
                            <img src={pic.original} alt="" onClick={() => handleImageClick(pic.original)} />
                            {/* <img src={pic.thumbnail} alt="" onClick={() => handleImageClick(pic.original)} /> */}
                        </React.Fragment>
                    ))}
            </div>
            <div className="productdisplay-img">
            {/* Render the main image */}
            <img className="productdisplay-main-img" src={mainImage} alt={product.name} />

            </div>
            </div> 
            <div className="productdisplay-right">
              <h1>{product.name}</h1>
              <div className='avatar_info1'>
                <div className="detail-row">
                    <strong>Gender:</strong> <span>{product.gender}</span>
                </div>
                <div className="detail-row">
                    <strong>Age Range:</strong> <span>{product.ageRange}</span>
                </div>
                <div className="detail-row">
                    <strong>Profile Type:</strong> <span>{product.profileType}</span>
                </div>
                <div className="detail-row">
                    <strong>Avatar Type:</strong> <span>{product.avatarType}</span>
                </div>
                <div className="detail-row">
                    <strong>Visibility:</strong> <span>{product.visibility}</span>
                </div>
                <div className="detail-row">
                    <strong>Generated By:</strong> <span>{product.generatedBy}</span>
                </div>
                <div className="detail-row">
                    <strong>Voice ID:</strong> <span>{product.voiceId}</span>
                </div>
                <div className="detail-row">
                    <strong>Operator ID:</strong> <span>{product.operatorId}</span>
                </div>
                <div className="detail-row">
                    <strong>Avatar ID:</strong> <span>{product.id}</span>
                </div>
                <div className="detail-row">
                    <strong>Profile Summary:</strong> <span>{product.profileSummary}</span>
                </div>
            </div>
            </div>
        </div>

    )
}

export default ProductDisplay